CreateLoginsTable: create table `logins` (`login_id` int unsigned not null auto_increment primary key, `username` varchar(16) not null, `password` varchar(255) not null, `token` varchar(255) null) default character set utf8mb4 collate utf8mb4_unicode_ci engine = InnoDB
CreatePositionsTable: create table `positions` (`position_id` int unsigned not null auto_increment primary key, `name` varchar(50) not null) default character set utf8mb4 collate utf8mb4_unicode_ci engine = InnoDB
CreatePositionsTable: alter table `positions` add unique `positions_name_unique`(`name`)
CreateProjectsTable: create table `projects` (`project_id` int unsigned not null auto_increment primary key, `name` varchar(200) not null, `address` varchar(255) not null, `time_in` time not null, `time_out` time not null, `active` tinyint(1) not null default '1') default character set utf8mb4 collate utf8mb4_unicode_ci engine = InnoDB
CreateProjectsTable: alter table `projects` add unique `projects_name_unique`(`name`)
CreateEmployeesTable: create table `employees` (`employee_id` int unsigned not null auto_increment primary key, `id_number` char(10) not null, `biometric_id` char(255) null, `account_number` char(25) not null, `last_name` varchar(50) not null, `first_name` varchar(100) not null, `middle_name` varchar(50) not null, `city_address` varchar(255) not null, `provincial_address` varchar(255) null, `birthdate` date not null, `civil_status` enum('Single', 'Married') not null, `number_of_dependencies` tinyint unsigned not null, `citizenship` varchar(30) not null, `religion` varchar(30) null, `gender` enum('Male', 'Female') not null, `sss_id` char(20) null, `tin_no` char(20) null, `phil_health_mp` char(20) null, `payroll_type` enum('Weekly', 'Monthly') not null, `date_started` date not null, `agency` tinyint(1) not null, `regular` tinyint(1) not null, `active` tinyint(1) not null, `position_id` int unsigned not null, `project_id` int unsigned not null) default character set utf8mb4 collate utf8mb4_unicode_ci engine = InnoDB
CreateEmployeesTable: alter table `employees` add unique `employees_id_number_unique`(`id_number`)
CreateEmployeesTable: alter table `employees` add unique `employees_biometric_id_unique`(`biometric_id`)
CreateEmployeesTable: alter table `employees` add unique `employees_account_number_unique`(`account_number`)
CreateSetActiveEmployeesEvent: create event set_active_employees on schedule every 1 day starts current_date + interval 1 day do update employees set active=1 where date_started=current_date;
AddForeignKeys: alter table `employees` add constraint `employees_position_id_foreign` foreign key (`position_id`) references `positions` (`position_id`)
AddForeignKeys: alter table `employees` add constraint `employees_project_id_foreign` foreign key (`project_id`) references `projects` (`project_id`)
